name: Arch

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Arch_Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://archlinux
        with:
          entrypoint: /usr/bin/bash
          run: git clone https://github.com/Myralllka/linux-setup.git && cd linux-setup && bash ./.ci/instal_arch.sh;